project:
  type: website

website:
  title: Data Fun
  navbar:
    right:
      - text: About
        href: https://auch.cool/about
      - icon: github
        href: https://github.com/flipez
format:
  html:
    theme: flatly
    css: styles.css



