[tools]
python = "3.13" # [optional] will be used for the venv

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist